In [19]:
RandomNumbers = [-0.23, 0.08, 0.81, 0.71, 0.85, -0.19, -0.63, 0.94, 0.19, 0.87, 0.64, -0.83]

bh = [0.06, 0.73, 0.34]

In [22]:
import numpy as np
x = np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

wh = np.array([[-0.23, 0.08, 0.81], [0.71, 0.85, -0.19],[-0.63, 0.94, 0.19], [0.87, 0.64, -0.83]])

biases = np.array([0.06, 0.73, 0.34])
hidden_layer_input = np.dot(x, wh)+ biases
print(hidden_layer_input)
#[[-0.8   1.75  1.34]
# [ 0.07  2.39  0.51]
# [ 1.64  2.22 -0.68]]

#Note: Sigmoid for claulation

[[-0.8   1.75  1.34]
 [ 0.07  2.39  0.51]
 [ 1.64  2.22 -0.68]]


In [23]:
import numpy as np
def sigmoid(x):
    return round(1 / (1 + np.exp(-x)),2)

hidden_layer_input = np.array([[-0.8,   1.75,  1.34],[ 0.07,  2.39,  0.51],[ 1.64,  2.22, -0.68]])
#hiddenlayer_activations =  relu(hidden_layer_input);
hiddenlayer_activations = np.array([[0.31   ,  0.85 ,  0.79 ],[0.51   ,  0.91 ,  0.62 ],[0.83   ,  0.90 ,  0.33 ]])
#[[0 ,  1.75,  1.34]
#[ 0.07,  2.39,  0.51]
#[ 1.64,  2.22, 0]]

bout = np.array([0.69])
wout = np.array([[0.36], [0.85], [0.98]])

output_layer_input = np.dot(hiddenlayer_activations,wout ) + bout
#[[ 2.2983],
#[ 2.2547],
#[ 2.0772]]

# output = sigmoid(output_layer_input)
output = np.array([[0.91],[0.91],[0.89]])
y = np.array([[1],[1],[0]])
Eout = y - output
print(Eout)
#[[ 0.09],
#[ 0.09],
#[-0.89]]

[[ 0.09]
 [ 0.09]
 [-0.89]]


In [24]:
def dsigmoid(y):
    return round(y * (1.0 - y),2)

In [26]:
import numpy as np
slope_hidden_layer = np.array([[  0.21, 0.13, 0.17],[  0.25, 0.08, 0.24],[  0.14, 0.09, 0.22]])
slope_output_layer = np.array([[0.08],[0.08],[0.10] ])
d_output = np.add(Eout, slope_output_layer)
print(d_output)

[[ 0.17]
 [ 0.17]
 [-0.79]]


In [28]:
Error_at_hidden_layer = np.dot(d_output, wout.T)
print(Error_at_hidden_layer)
#[[ 0.0612  0.1445  0.1666]
# [ 0.0612  0.1445  0.1666]
# [-0.2844 -0.6715 -0.7742]]

d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
print(d_hiddenlayer)
#[[ 0.012852  0.018785  0.028322]
# [ 0.0153    0.01156   0.039984]
# [-0.039816 -0.060435 -0.170324]]

[[ 0.0612  0.1445  0.1666]
 [ 0.0612  0.1445  0.1666]
 [-0.2844 -0.6715 -0.7742]]
[[ 0.012852  0.018785  0.028322]
 [ 0.0153    0.01156   0.039984]
 [-0.039816 -0.060435 -0.170324]]


In [35]:
learning_rate = 0.1
wout = wout + np.dot(hiddenlayer_activations.T, d_output) * learning_rate
print(wout)
#[-0.00141]
# [ 0.56174]
# [ 0.9653 ]]

wh = wh + np.dot(x.T,d_hiddenlayer) * learning_rate
print(wh)
#[[-0.2102936  0.1012415  0.8578142]
# [ 0.6821288  0.8076955 -0.3092268]
# [-0.6102936  0.9612415  0.2378142]
# [ 0.8528388  0.6057875 -0.921238 ]]

[[-0.00141]
 [ 0.56174]
 [ 0.9653 ]]
[[-0.2102936  0.1012415  0.8578142]
 [ 0.6821288  0.8076955 -0.3092268]
 [-0.6102936  0.9612415  0.2378142]
 [ 0.8528388  0.6057875 -0.921238 ]]


In [36]:
bh = bh + np.sum(d_hiddenlayer, axis=0) * learning_rate
print(bh)
#[[ 0.13126924  0.83085168  0.51976231]]

bout = bout + np.sum(d_output, axis=0)*learning_rate
print(bout)
#[ 0.645]

[[ 0.13126924  0.83085168  0.51976231]]
[ 0.645]


In [38]:
# Another example 

import numpy as np

#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))



#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
    return x * (1 - x)



#Variable initialization
epoch=100 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):

    #Forward Propogation
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    E = y-output
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    d_output = E * slope_output_layer
    Error_at_hidden_layer = d_output.dot(wout.T)
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

    print(output)

[[ 0.82729681]
 [ 0.84430268]
 [ 0.82620679]]
[[ 0.8248064 ]
 [ 0.84173301]
 [ 0.82326586]]
[[ 0.82229778]
 [ 0.83913906]
 [ 0.82029603]]
[[ 0.81977263]
 [ 0.83652247]
 [ 0.81729911]]
[[ 0.81723273]
 [ 0.83388503]
 [ 0.814277  ]]
[[ 0.81467992]
 [ 0.83122856]
 [ 0.81123169]]
[[ 0.81211614]
 [ 0.82855503]
 [ 0.80816528]]
[[ 0.80954337]
 [ 0.82586646]
 [ 0.80507996]]
[[ 0.80696368]
 [ 0.82316497]
 [ 0.801978  ]]
[[ 0.8043792 ]
 [ 0.82045274]
 [ 0.79886174]]
[[ 0.80179209]
 [ 0.81773202]
 [ 0.7957336 ]]
[[ 0.79920457]
 [ 0.81500513]
 [ 0.79259603]]
[[ 0.7966189 ]
 [ 0.81227442]
 [ 0.78945155]]
[[ 0.79403736]
 [ 0.8095423 ]
 [ 0.78630273]]
[[ 0.79146223]
 [ 0.80681119]
 [ 0.78315213]]
[[ 0.78889583]
 [ 0.80408354]
 [ 0.78000235]]
[[ 0.78634045]
 [ 0.80136183]
 [ 0.776856  ]]
[[ 0.7837984 ]
 [ 0.79864852]
 [ 0.77371568]]
[[ 0.78127194]
 [ 0.79594605]
 [ 0.77058395]]
[[ 0.77876332]
 [ 0.79325686]
 [ 0.76746337]]
[[ 0.77627475]
 [ 0.79058336]
 [ 0.76435645]]
[[ 0.77380839]
 [ 0.78792791]
 [ 0